const A=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={starts:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(c,n,r){const a=new Float32Array(n);return{length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)}}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){}}}}window.AudioContext=C;window.webkitAudioContext=C};
const cases={
"soundhelp":async(p,click,select,check)=>{A.equal(await p.locator('#bend-rule-expression').textContent(),'y(t) = sin(2π × 220 × t + I(t) × sin(2π × M × t + 2π × φ)). I(t) is the phase index at that instant in radians; M is the modulator frequency in hertz; φ is the source start in cycles.');const d=p.locator('#bend-sound-guide');A.equal(await d.evaluate(e=>e.open),false);for(const id of ['bend-compare-plain-help','bend-sources-help','bend-fall-help']){A.equal(await p.locator('#'+id).evaluate(e=>e.closest('details').id),'bend-sound-guide');A.equal(await p.locator('#'+id).evaluate(e=>e.checkVisibility()),false)}A(await p.locator('#bend-sound-help').evaluate(e=>e.checkVisibility()));A(await p.locator('#bend-listen').evaluate(e=>e.checkVisibility()));await click('bend-listen');await click('bend-stop');const q=d.locator(':scope>summary');await q.scrollIntoViewIfNeeded();await q.focus();await p.keyboard.press('Enter');A(await d.evaluate(e=>e.open));A(await p.locator('#bend-fall-help').evaluate(e=>e.checkVisibility()));A.equal(await p.locator('#bend-memory').evaluate(e=>e.open),false);},
"lowratio":async(p,click,select,check)=>{for(const [r,h,q,x] of [['0.5','110',2,200],['0.6666666666666666','146.66666666666666',3,294]]){await select('bend-ratio',r);A((await p.locator('#bend-values').innerText()).includes('modulator: '+h+' Hz'));A.equal(await p.locator('#bend-repeat-readout').innerText(),`Frozen wave repeats after ${q} carrier cycles.`);A.equal(Number(await p.locator('#bend-repeat-line').getAttribute('x2')),x)}await click('bend-keep');await select('bend-ratio','1');await click('bend-return');A.equal(await p.locator('#bend-ratio').inputValue(),'0.6666666666666666');await p.locator('#bend-index').fill('0');await p.locator('#bend-index').press('ArrowRight');await p.locator('#bend-index').fill('0');A.equal(await p.locator('#bend-repeat-readout').innerText(),'Frozen wave repeats after 1 carrier cycle.');A.equal(await p.evaluate(()=>__audio.starts),0);}
};
const messages={"soundhelp": "sound explanations fold while the controls and volume caution remain visible", "lowratio": "a slower bending source marks two and three carrier cycles and survives Return"};

(async()=>{A(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(e.message));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(120);
const reveal=async l=>{const ids=await l.evaluate(e=>{let a=[];for(let n=e.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS'&&!n.open)a.unshift(n.id);return a});for(const id of ids){A(id);await p.locator('#'+id+'>summary').scrollIntoViewIfNeeded();await p.locator('#'+id+'>summary').click()}};
const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A(await l.isEnabled(),id+' enabled');A(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}),id+' hit');await l.click();await p.waitForTimeout(70)};
const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(70)};
const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(70)};
await cases[mode](p,click,select,check);A.deepEqual(errors,[]);A(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/planner-oct9-${mode}-${width}.png`,fullPage:true});await p.close();}console.log(messages[mode]);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
