const A=require('node:assert/strict'),{chromium}=require('playwright-core');const mode=process.argv[2],url=process.argv[3];
const messages={wave:'a sine inside a sine changes the drawn wave without autoplay',sound:'one finite note plays the authored samples and stops without autoplay',keep:'a kept bend remains independent and can be heard or returned explicitly',fall:'the bend can fall while the note amplitude envelope stays the same'};
async function reveal(p,e){const ids=await e.evaluate(el=>{let a=[];for(let n=el.tagName==='SUMMARY'?el.parentElement.parentElement:el.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS'&&!n.open)a.unshift(n.id);return a});for(const id of ids){const s=p.locator('#'+id+'>summary');await s.scrollIntoViewIfNeeded();A(await s.evaluate(el=>{const r=el.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===el||el.contains(h)}));await s.click()}}
async function click(p,id){const e=p.locator('#'+id);await reveal(p,e);await e.scrollIntoViewIfNeeded();A(await e.isEnabled(),id);A((await e.boundingBox()).height>=44,id+' size');A(await e.evaluate(e=>{const r=e.getBoundingClientRect(),t=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return t===e||e.contains(t)}),id+' hit');await e.click()}
async function range(p,id,v){const e=p.locator('#'+id);await reveal(p,e);await e.scrollIntoViewIfNeeded();await e.focus();await p.keyboard.press('Home');const min=+(await e.getAttribute('min')),step=+(await e.getAttribute('step'));for(let i=min;i<v-1e-9;i+=step)await p.keyboard.press('ArrowRight')}
const sample=(t,r,I)=>Math.sin(2*Math.PI*220*t+I*Math.sin(2*Math.PI*220*r*t));const env=t=>Math.max(0,Math.min(1,t/.01,(.8-t)/.04));
async function wave(p,id,r,I){const pts=(await p.locator('#'+id).getAttribute('points')).trim().split(/\s+/).map(s=>s.split(',').map(Number));A.equal(pts.length,401);for(const i of [0,13,50,123,200,337,400]){A(Math.abs(pts[i][0]-(12+376*i/400))<.0001);A(Math.abs(pts[i][1]-(80-60*sample((4/220)*i/400,r,I)))<.0001)}}
(async()=>{A(messages[mode]);const b=await chromium.launch({args:['--no-sandbox']});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.__audioLog={created:0,starts:0,stops:0,buffers:[]};const C=window.AudioContext;window.AudioContext=class extends C{constructor(...a){super(...a);window.__audioLog.created++}createBuffer(...a){const x=super.createBuffer(...a);window.__audioLog.buffers.push(x);return x}createBufferSource(){const x=super.createBufferSource();const start=x.start.bind(x),stop=x.stop.bind(x);x.start=(...a)=>{window.__audioLog.starts++;return start(...a)};x.stop=(...a)=>{window.__audioLog.stops++;return stop(...a)};return x}}});A.equal((await p.goto(url)).status(),200);A.equal(await p.title(),'Bend a sine');await wave(p,'bend-wave',1,2);A.equal(await p.evaluate(()=>window.__audioLog.created),0);
if(mode==='wave'){await range(p,'bend-index',0);await wave(p,'bend-wave',1,0);await p.selectOption('#bend-ratio','1.5');await range(p,'bend-index',4);await wave(p,'bend-wave',1.5,4);A.equal(await p.locator('#bend-values').innerText(),'Carrier: 220 Hz · modulator: 330 Hz · index: 4.00.');A.equal(await p.evaluate(()=>window.__audioLog.created),0);}
if(mode==='sound'||mode==='fall'){if(mode==='fall'){await p.selectOption('#bend-mode','falling');await p.selectOption('#bend-moment','0.3');await wave(p,'bend-wave',1,1);A.equal(await p.locator('#bend-index-here').innerText(),'Index here: 1.00 at 0.30 seconds.');await p.selectOption('#bend-moment','0.6');await wave(p,'bend-wave',1,0)}await click(p,'bend-listen');await p.waitForFunction(()=>window.__audioLog.starts===1);const data=await p.evaluate(()=>{const b=window.__audioLog.buffers.at(-1);return {rate:b.sampleRate,length:b.length,channels:b.numberOfChannels,values:[0,1,123,1001,7777,b.length-1].map(i=>[i,b.getChannelData(0)[i]])}});A.equal(data.channels,1);A.equal(data.length,Math.round(data.rate*.8));for(const [i,v]of data.values){const t=i/data.rate,I=mode==='fall'?2*Math.max(0,1-t/.6):2;A(Math.abs(v-.15*env(t)*sample(t,1,I))<1e-7)}await p.waitForTimeout(1000);A.equal(await p.locator('#bend-sound-status').innerText(),'Ready.');A(await p.locator('#bend-stop').isDisabled());await click(p,'bend-listen');await click(p,'bend-stop');A((await p.evaluate(()=>window.__audioLog.stops))>=1);await p.selectOption('#bend-ratio','2');A.equal(await p.evaluate(()=>window.__audioLog.starts),2);}
if(mode==='keep'){A(await p.locator('#bend-return').isDisabled());await click(p,'bend-keep');await range(p,'bend-index',4);await p.selectOption('#bend-ratio','2');await wave(p,'bend-kept-wave',1,2);await wave(p,'bend-wave',2,4);const current=await p.locator('#bend-values').innerText();await click(p,'bend-listen-kept');await p.waitForFunction(()=>window.__audioLog.starts===1);A.equal(await p.locator('#bend-values').innerText(),current);await click(p,'bend-stop');await click(p,'bend-return');await wave(p,'bend-wave',1,2);A(await p.locator('#bend-return').isDisabled());await range(p,'bend-index',3);await click(p,'bend-forget');A(await p.locator('#bend-return').isDisabled());A(await p.locator('#bend-listen-kept').isDisabled());A.equal(await p.locator('#bend-kept-wave').evaluate(e=>e.checkVisibility()),false);}
A.deepEqual(errors,[]);A.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:`/tmp/bend-${mode}-${width}.png`,fullPage:true});await p.close()}console.log(messages[mode])}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
