const cases={
"rise":async(p,click,select,check)=>{await select('bend-mode','rising');await select('bend-moment','0.6');A.equal(await p.locator('#bend-index-here').innerText(),'Index here: 2.00 at 0.60 seconds.');const r=await p.evaluate(async()=>{const m=await import('/model.mjs?pm='+Date.now());return [.0,.3,.6,.8].map(t=>m.indexAt(t,{index:2,bend:'rising'}))});A.deepEqual(r,[0,1,2,2]);await click('bend-listen');A.equal(await p.evaluate(()=>__audio.buffers.at(-1).length),38400);await click('bend-stop');},
"modphase":async(p,click,select,check)=>{await select('bend-phase','0.25');await click('bend-keep');await select('bend-phase','0');await click('bend-return');A.equal(await p.locator('#bend-phase').inputValue(),'0.25');const r=await p.evaluate(async()=>{const m=await import('/model.mjs?pm='+Date.now());return m.sample(0,{ratio:1,index:2,phase:.25})});A.ok(Math.abs(r-Math.sin(2))<1e-12);A.equal(await p.evaluate(()=>__audio.starts),0);},
"drypair":async(p,click,select,check)=>{await click('bend-compare-plain');const r=await p.evaluate(()=>{const b=__audio.buffers.at(-1),a=b.getChannelData(0);return {n:b.length,mid:a[45000],start2:a[50400],plain:a[480],starts:__audio.starts}});A.equal(r.n,88800);A.equal(r.mid,0);A.equal(r.start2,0);A.ok(Math.abs(r.plain-.15*Math.sin(2*Math.PI*220*.01))<1e-7);A.equal(r.starts,1);await click('bend-stop');}
};
const messages={"rise": "a rising bend changes phase index without changing the finite amplitude envelope", "modphase": "bending phase is kept and returned without starting another note", "drypair": "plain then bent notes share one envelope and a silent gap"};
const A=require('node:assert/strict'),{chromium}=require('playwright-core');const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={buffers:[],starts:0,stops:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(ch,n,r){const a=new Float32Array(n);const b={length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)};__audio.buffers.push(b);return b}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){__audio.stops++},loop:false}}}window.AudioContext=C;window.webkitAudioContext=C};
(async()=>{A.ok(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});for(const width of[390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(String(e)));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(100);const reveal=async l=>{const ds=await l.evaluate(e=>{let a=[];for(let x=e.parentElement;x;x=x.parentElement)if(x.tagName==='DETAILS'&&!x.open)a.unshift(x.id);return a});for(const d of ds){const s=p.locator('#'+d+'>summary');await s.scrollIntoViewIfNeeded();await s.click()}};const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A.ok(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}));await l.click();await p.waitForTimeout(60)};const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(60)};const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(60)};await cases[mode](p,click,select,check);A.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));A.deepEqual(errors,[]);await p.screenshot({path:`/tmp/pm-${mode}-${width}.png`,fullPage:true});await p.close()}await b.close();console.log(messages[mode])})().catch(e=>{console.error(e);process.exit(1)});
